// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlLkwcwql_1JXJ6QKunTIZpgiyxeOdUH0',
    appId: '1:723764254473:web:ae379343b5520a5e9aa5d8',
    messagingSenderId: '723764254473',
    projectId: 'motorbike-rescue',
    authDomain: 'motorbike-rescue.firebaseapp.com',
    storageBucket: 'motorbike-rescue.firebasestorage.app',
    measurementId: 'G-SWPWP8BHJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUIIK0Hwt8zYi4O5Mf3eFbqayaayaLEzw',
    appId: '1:723764254473:android:2aedb0e848fc65319aa5d8',
    messagingSenderId: '723764254473',
    projectId: 'motorbike-rescue',
    storageBucket: 'motorbike-rescue.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOrv1J1NuwK91z2imwh13luG8tVwoJ3CA',
    appId: '1:723764254473:ios:94329d98064050d09aa5d8',
    messagingSenderId: '723764254473',
    projectId: 'motorbike-rescue',
    storageBucket: 'motorbike-rescue.firebasestorage.app',
    iosBundleId: 'com.example.motorbikeRescueApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOrv1J1NuwK91z2imwh13luG8tVwoJ3CA',
    appId: '1:723764254473:ios:94329d98064050d09aa5d8',
    messagingSenderId: '723764254473',
    projectId: 'motorbike-rescue',
    storageBucket: 'motorbike-rescue.firebasestorage.app',
    iosBundleId: 'com.example.motorbikeRescueApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlLkwcwql_1JXJ6QKunTIZpgiyxeOdUH0',
    appId: '1:723764254473:web:bb3d40c8aa2147669aa5d8',
    messagingSenderId: '723764254473',
    projectId: 'motorbike-rescue',
    authDomain: 'motorbike-rescue.firebaseapp.com',
    storageBucket: 'motorbike-rescue.firebasestorage.app',
    measurementId: 'G-HN6PZHGYTG',
  );
}
